name: ejabberd
version: "16.08"
summary: ejabberd XMPP server
description: ejabberd is a Jabber/XMPP server written in Erlang
confinement: strict

parts:
  ejabberd:
    plugin: autotools
    source: https://github.com/processone/ejabberd.git
    source-tag: "16.08"
    source-type: git
    configflags: [--enable-all]
    build-packages:
      - build-essential
      - erlang-dev
      - erlang-eunit
      - erlang-parsetools
      - hevea
      - libexpat1-dev
      - libpam0g-dev
      - libsqlite3-dev
      - libssl-dev
      - libyaml-dev
      - po-debconf
      - rebar
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
    stage-packages:
      - erlang-asn1
      - erlang-base
      - erlang-crypto
      - erlang-inets
      - erlang-mnesia
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-xmerl
  wrapper:
    plugin: copy
    source: .
    files:
      ejabberdctl.wrapper: bin/ejabberdctl.wrapper

apps:
  ejabberd:
    command: bin/ejabberdctl.wrapper start
    stop-command: bin/ejabberdctl.wrapper stop
    daemon: forking
    plugs:
      - network
      - network-bind
  ejabberdctl:
    command: bin/ejabberdctl.wrapper
    plugs:
      - network
      - network-bind
