name: ejabberd
version: "16.09"
summary: ejabberd XMPP server
description: ejabberd is a Jabber/XMPP server written in Erlang
confinement: strict
grade: stable

parts:
  ejabberd:
    plugin: autotools
    source: https://github.com/processone/ejabberd.git
    source-tag: "16.09"
    source-type: git
    configflags:
      - --enable-odbc
      - --enable-mysql
      - --enable-pgsql
      - --enable-pam
      - --enable-zlib
      - --enable-riak
      - --enable-redis
      - --enable-elixir
      - --enable-iconv
      - --enable-debug
      - --enable-tools
    build-packages:
      - build-essential
      - erlang-dev
      - erlang-eunit
      - erlang-parsetools
      - hevea
      - libexpat1-dev
      - libpam0g-dev
      - libsqlite3-dev
      - libssl-dev
      - libyaml-dev
      - po-debconf
      - rebar
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
    stage-packages:
      - erlang-asn1
      - erlang-base
      - erlang-crypto
      - erlang-inets
      - erlang-mnesia
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-xmerl
  wrapper:
    plugin: dump
    source: .
    organize:
      ejabberdctl.wrapper: bin/ejabberdctl.wrapper

apps:
  ejabberd:
    command: bin/ejabberdctl.wrapper start
    stop-command: bin/ejabberdctl.wrapper stop
    daemon: forking
    plugs:
      - network
      - network-bind
  ejabberdctl:
    command: bin/ejabberdctl.wrapper
    plugs:
      - network
      - network-bind
